const protobuf = require('protobufjs');
const path = require('path');

const loadProto = async (topic) => {
    
    let evmFiles = [
        'evm/dex_block_message.proto', 
        'evm/token_block_message.proto', 
        'evm/block_message.proto', 
        'evm/parsed_abi_block_message.proto',
        'evm/dex_pool_block_message.proto',
        'evm/prediction_market_block_message.proto'
    ];

    let evmMessages = [
        'evm_messages.DexBlockMessage', 
        'evm_messages.TokenBlockMessage',
        'evm_messages.BlockMessage',
        'evm_messages.ParsedAbiBlockMessage',
        'evm_messages.DexPoolBlockMessage',
        'evm_messages.PredictionMarketBlockMessage'
    ];

    let tronFiles = [
        'tron/dex_block_message.proto', 
        'tron/token_block_message.proto', 
        'tron/block_message.proto', 
        'tron/parsed_abi_block_message.proto'
    ]

    let tronMessages = [
        'tron_messages.DexBlockMessage', 
        'tron_messages.TokenBlockMessage',
        'tron_messages.BlockMessage',
        'tron_messages.ParsedAbiBlockMessage',
    ];

    let topicToPath = {
        'bsc.dextrades.proto': evmFiles[0],
        'bsc.tokens.proto': evmFiles[1],
        'bsc.transactions.proto': evmFiles[3],
        'bsc.dexpools.proto': evmFiles[4],
        'bsc.broadcasted.dextrades.proto': evmFiles[0],
        'bsc.broadcasted.tokens.proto': evmFiles[1],
        'bsc.broadcasted.raw.proto': evmFiles[2],
        'bsc.broadcasted.transactions.proto': evmFiles[3],
        'bsc.broadcasted.dexpools.proto': evmFiles[4],
        'eth.dextrades.proto': evmFiles[0],
        'eth.tokens.proto': evmFiles[1],
        'eth.transactions.proto': evmFiles[3],
        'eth.dexpools.proto': evmFiles[4],
        'eth.broadcasted.dextrades.proto': evmFiles[0],
        'eth.broadcasted.tokens.proto': evmFiles[1],
        'eth.broadcasted.raw.proto': evmFiles[2],
        'eth.broadcasted.transactions.proto': evmFiles[3],
        'eth.broadcasted.dexpools.proto': evmFiles[4],
        'base.dextrades.proto': evmFiles[0],
        'base.tokens.proto': evmFiles[1],
        'base.raw.proto': evmFiles[2],
        'base.transactions.proto': evmFiles[3],
        'base.dexpools.proto': evmFiles[4],
        'arbitrum.dextrades.proto':evmFiles[0],
        'arbitrum.tokens.proto':evmFiles[1],
        'arbitrum.transactions.proto':evmFiles[3],
        'arbitrum.dexpools.proto': evmFiles[4],
        'matic.dextrades.proto': evmFiles[0],
        'matic.tokens.proto': evmFiles[1],
        'matic.transactions.proto': evmFiles[3],
        'matic.dexpools.proto': evmFiles[4],
        'matic.broadcasted.dextrades.proto': evmFiles[0],
        'matic.broadcasted.tokens.proto': evmFiles[1],
        'matic.broadcasted.transactions.proto': evmFiles[3],
        'matic.broadcasted.dexpools.proto': evmFiles[4],
        'optimism.dextrades.proto': evmFiles[0],
        'optimism.tokens.proto': evmFiles[1],
        'optimism.transactions.proto': evmFiles[3],
        'optimism.dexpools.proto': evmFiles[4],
        'robinhood.dextrades.proto':evmFiles[0],
        'robinhood.tokens.proto':evmFiles[1],
        'robinhood.transactions.proto':evmFiles[3],
        'robinhood.dexpools.proto': evmFiles[4],
        'solana.transactions.proto': 'solana/parsed_idl_block_message.proto',
        'solana.tokens.proto': 'solana/token_block_message.proto',
        'solana.dextrades.proto': 'solana/dex_block_message.proto',
        'solana.perpetual.proto': 'solana/perpetual_block_message.proto',
        'tron.dextrades.proto': tronFiles[0],
        'tron.tokens.proto': tronFiles[1],
        'tron.transactions.proto': tronFiles[3],
        'tron.broadcasted.dextrades.proto': tronFiles[0],
        'tron.broadcasted.tokens.proto': tronFiles[1],
        'tron.broadcasted.transactions.proto': tronFiles[3],
        'btc.transactions.proto': 'utxo/parsed_block_message.proto',
        'trading.prices': 'market/price_index.proto',
        'trading.trades': 'market/trades.proto',
        'matic.predictions.proto': evmFiles[5],
        'matic.broadcasted.predictions.proto': evmFiles[5],
        'hyperliquidcore.messages.proto': 'hyperliquid/hyperliquid_block_message.proto',
        'hyperliquid.candles.proto': 'hyperliquid/candles.proto',
    }

    let topicToMessage = {
        'bsc.dextrades.proto': evmMessages[0],
        'bsc.tokens.proto': evmMessages[1],
        'bsc.transactions.proto': evmMessages[3],
        'bsc.dexpools.proto': evmMessages[4],
        'bsc.broadcasted.dextrades.proto': evmMessages[0],
        'bsc.broadcasted.tokens.proto': evmMessages[1],
        'bsc.broadcasted.raw.proto': evmMessages[2],
        'bsc.broadcasted.transactions.proto': evmMessages[3],
        'bsc.broadcasted.dexpools.proto': evmMessages[4],
        'eth.dextrades.proto': evmMessages[0],
        'eth.tokens.proto': evmMessages[1],
        'eth.transactions.proto': evmMessages[3],
        'eth.dexpools.proto': evmMessages[4],
        'eth.broadcasted.dextrades.proto': evmMessages[0],
        'eth.broadcasted.tokens.proto': evmMessages[1],
        'eth.broadcasted.raw.proto': evmMessages[2],
        'eth.broadcasted.transactions.proto': evmMessages[3],
        'eth.broadcasted.dexpools.proto': evmMessages[4],
        'base.dextrades.proto': evmMessages[0],
        'base.tokens.proto': evmMessages[1],
        'base.raw.proto': evmMessages[2],
        'base.transactions.proto': evmMessages[3],
        'base.dexpools.proto': evmMessages[4],
        'arbitrum.dextrades.proto':evmMessages[0],
        'arbitrum.tokens.proto':evmMessages[1],
        'arbitrum.transactions.proto':evmMessages[3],
        'arbitrum.dexpools.proto': evmMessages[4],
        'matic.dextrades.proto': evmMessages[0],
        'matic.tokens.proto': evmMessages[1],
        'matic.transactions.proto': evmMessages[3],
        'matic.dexpools.proto': evmMessages[4],
        'matic.broadcasted.dextrades.proto': evmMessages[0],
        'matic.broadcasted.tokens.proto': evmMessages[1],
        'matic.broadcasted.transactions.proto': evmMessages[3],
        'matic.broadcasted.dexpools.proto': evmMessages[4],
        'optimism.dextrades.proto': evmMessages[0],
        'optimism.tokens.proto': evmMessages[1],
        'optimism.transactions.proto': evmMessages[3],
        'optimism.dexpools.proto': evmMessages[4],
        'robinhood.dextrades.proto':evmMessages[0],
        'robinhood.tokens.proto':evmMessages[1],
        'robinhood.transactions.proto':evmMessages[3],
        'robinhood.dexpools.proto': evmMessages[4],
        'solana.transactions.proto': 'solana_messages.ParsedIdlBlockMessage',
        'solana.tokens.proto': 'solana_messages.TokenBlockMessage',
        'solana.dextrades.proto': 'solana_messages.DexParsedBlockMessage',
        'solana.perpetual.proto': 'solana_messages.PerpetualBlockMessage',
        'tron.dextrades.proto': tronMessages[0],
        'tron.tokens.proto': tronMessages[1],
        'tron.transactions.proto': tronMessages[3],
        'tron.broadcasted.dextrades.proto': tronMessages[0],
        'tron.broadcasted.tokens.proto': tronMessages[1],
        'tron.broadcasted.transactions.proto': tronMessages[3],
        'btc.transactions.proto': 'utxo_messages.ParsedBlockMessage',
        'trading.prices': 'marketdata_messages.PriceIndexMessage',
        'trading.trades': 'marketdata_messages.TradesMessage',
        'matic.predictions.proto': evmMessages[5],
        'matic.broadcasted.predictions.proto': evmMessages[5],
        'hyperliquidcore.messages.proto': 'hyperliquid_messages.HyperliquidCoreBlockMessage',
        'hyperliquid.candles.proto': 'hyperliquid_messages.CandlesBlockMessage',
    }

    const filePath = path.join(__dirname, topicToPath[topic])
    const root = await protobuf.load(filePath);
    return root.lookupType(topicToMessage[topic]);
}; 

module.exports = {loadProto};